// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaperFeed.Infrastructure.DataAccess;

#nullable disable

namespace PaperFeed.Infrastructure.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20250611215005_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("PaperFeed.Application.Models.PostedImage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderedId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderedId")
                        .IsDescending();

                    b.ToTable("PostedImages");
                });
#pragma warning restore 612, 618
        }
    }
}
